"""empty message

Revision ID: 697fde4c0937
Revises: 3d4023c9b8ee
Create Date: 2018-06-08 17:25:07.660595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697fde4c0937'
down_revision = '3d4023c9b8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qx',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('right', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('rights', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('t_user', sa.Column('reghts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'reghts')
    op.drop_table('role')
    op.drop_table('qx')
    # ### end Alembic commands ###
